sudo: required
services:
  - docker


before_install:
  - docker build -t bader/react-test -b ./client/Dockerfile.dev ./client

script:
  - docker run bader/react-test npm test -- --coverage

after_success:
  - docker build -t bader/multi-client ./client
  - docker build -t bader/multi-nginx ./nginx
  - docker build -t bader/multi-server ./server
  - docker build -t bader/multi-worker ./worker
